theme: jekyll-theme-cayman
title: Mobile Checkers For Android
description: This project was created for a mobile app development to showcase the ability to create and build projects in unity and run them on Android Based phones.
